hpt/api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers

import acls.views
import inventory.views
import core.views


router = routers.DefaultRouter()
router.register(r'acls', acls.views.AccessListViewSet)
router.register(r'inventory', inventory.views.NetDeviceViewSet)
router.register(r'task', core.views.TaskStateViewSet)
router.register(r'task_meta', core.views.TaskMetaViewSet)
router.register(r'workers', core.views.WorkerStateViewSet)


urlpatterns = patterns(__name__,
    url(r'^', include(router.urls)),
)

hpt/core/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import routers
from core import views


router = routers.DefaultRouter()
router.register(r'task', views.TaskStateViewSet)
router.register(r'task_meta', views.TaskMetaViewSet)


urlpatterns = patterns(__name__,
    url(r'^', include(router.urls)),
)

hpt/hpt/urls.py
from django.conf.urls import patterns, include, url

# import xadmin
# xadmin.autodiscover()

#from xadmin.plugins import xversion
#xversion.register_models()

from django.contrib import admin
admin.autodiscover()

"""
from rest_framework import routers
from inventory import views
router = routers.DefaultRouter()
router.register(r'inventory', views.NetDeviceViewSet)
"""

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hpt.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Xadmin
    # url(r'^', include(xadmin.site.urls)),
    url(r'^', include(admin.site.urls)),

    # Change password
    url(r'^change_password/', 'core.views.change_password'),

    # Inventory API
    #url(r'^api/', include(router.urls)),
    #url(r'^api/', include('inventory.urls')),
    #url(r'^api/', include('core.urls')),
    url(r'^api/', include('api.urls')),

    # Django REST Framework
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework')),

    # Inventory
    url(r'^netdevices/$', 'inventory.views.netdevice_list'),
)

#from django.conf import settings
#if settings.DEBUG:
#    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#    urlpatterns += staticfiles_urlpatterns()

hpt/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from djcelery.models import TaskMeta, TaskState, WorkerState

# Create your models here.
#User = get_user_model()

"""
class Task(models.Model):
    user = models.ForeignKey(User)
    executed = models.DateTimeField() # NYI
"""


'''
class TaskEvent(TaskState):
    """Union of TaskMeta and TaskState data."""
    def __init__(self, *args, **kwargs):
        super(TaskEvent, self).__init__(*args, **kwargs)
        self._task_meta = TaskMeta.objects.get(task_id=self.task_id)

    class Meta:
        proxy = True

    # These are all the fields that can be found on the TaskMeta instance
    @property
    def date_done(self):
        return self._task_meta.date_done

    @property
    def full_result(self):
        return self._task_meta.result

    @property
    def hidden(self):
        return self._task_meta.hidden
'''

hpt/core/forms.py
from django.conf import settings
from django import forms
from django.forms import ValidationError as FormValidationError

import json
import requests

class ChangePasswordForm(forms.Form):
    """
    Form for changing device passwords.
    """
    devices = forms.CharField(
        label='Devices',
        widget=forms.Textarea,
        help_text=(
            'Devices on which you would like to set the new password. '
            'One per line.'
        ),
    )
    new_password = forms.CharField(
        label='New Password',
        help_text=(
            'The new password you would like apply to these devices.'
        )
    )

    def clean_devices(self):
        """Convert devices into a list"""
        devices = self.cleaned_data.get('devices')
        try:
            devices = devices.splitlines()
        except (TypeError, AttributeError) as err:
            raise FormValidationError(str(err))
        else:
            return devices

    def save(self, commit=True):
        """
        Given valid devices, password, execute the task
        """
        #print 'SUCCESS'
        kwargs = self.cleaned_data
        data = dict(kwargs=kwargs)
        payload = json.dumps(data)
        url = 'http://ops.lab.hollow.pt:5555/api/task/async-apply/core.tasks.change_password'
        r = requests.post(url, data=payload)
        rdata = r.json()
        return rdata['task-id']

from inventory.models import NetDevice
class ShowClockForm(forms.Form):
    """
    Form for fetching the time on devices.
    """
    devices = forms.ModelChoiceField(
        label='Devices',
        queryset=NetDevice.objects.all(),
        #widget=forms.Textarea,
        help_text=(
            'Devices on which you would like to get the time. '
            'One per line.'
        ),
    )

    '''
    def clean_devices(self):
        """Convert devices into a list"""
        devices = self.cleaned_data.get('devices')
        try:
            devices = devices.splitlines()
        except (TypeError, AttributeError) as err:
            raise FormValidationError(str(err))
        else:
            return devices
    '''

    def save(self, commit=True):
        """
        Given valid devices, password, execute the task
        """
        #print 'SUCCESS'
        kwargs = self.cleaned_data
        data = dict(kwargs=kwargs)
        payload = json.dumps(data)
        url = 'http://ops.lab.hollow.pt:5555/api/task/async-apply/core.tasks.show_clock'
        r = requests.post(url, data=payload)
        rdata = r.json()
        return rdata['task-id']

hpt/core/views.py
from django.shortcuts import render

# Create your views here.
#from celery import registry
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt


import forms
# Create your views here.

@csrf_exempt
def change_password(request):
    if request.method == 'POST':
        data = request.POST
        form = forms.ChangePasswordForm(data)
        if form.is_valid():
            task_id = form.save()
            # url = 'http://ops.lab.hollow.pt:5555/task/' + task_id
            url = 'http://localhost:5555/task/' + task_id
            return HttpResponseRedirect(url)

            #return render_to_response(
            #    'change_password_form.html',
            #    {'form': form, 'task_id': task_id}
            #)
    else:
        form = forms.ChangePasswordForm()
    return render_to_response('change_password_form.html', {'form': form})


from .models import TaskState, TaskMeta, WorkerState
from rest_framework import viewsets
from .serializers import (TaskStateSerializer, TaskMetaSerializer,
                          WorkerStateSerializer)
class TaskStateViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows TaskState objects to be viewed.
    """
    queryset = TaskState.objects.all()
    serializer_class = TaskStateSerializer
    # lookup_field = 'task_id'

    # class Meta:
    #     exclude = ('worker',)


class WorkerStateViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows WorkerState objects to be viewd.
    """
    queryset = WorkerState.objects.all()
    serializer_class = WorkerStateSerializer


class TaskMetaViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows TaskMeta objects to be viewed.
    """
    queryset = TaskMeta.objects.all()
    serializer_class = TaskMetaSerializer

hpt/core/templates/change_password_form.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <!--
        <fieldset class="grp-module wide">
            <div class="grp-row grp-cells-1 username ">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1">
                        <label class="required" for="id_devices">Devices</label>
                    </div>
                    <div class="c-2">
                        <textarea id="id_devices" maxlength="30" name="devices" type="text" />
                            <p class="grp-help">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</p></div></div></div><div class="grp-row grp-cells-1 password1 "><div class="l-2c-fluid l-d-4"><div class="c-1"><label class="required" for="id_password1">Password</label></div><div class="c-2"><input id="id_password1" name="password1" type="password" /></div></div></div><div class="grp-row grp-cells-1 password2 "><div class="l-2c-fluid l-d-4"><div class="c-1"><label class="required" for="id_password2">Password confirmation</label></div><div class="c-2"><input id="id_password2" name="password2" type="password" /><p class="grp-help">Enter the same password as above, for verification.</p></div></div></div></fieldset>
        -->
        <!--
        <table>
            {{ form.as_table }}
        </table>
        -->
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" value="Change Password!">
    </form>
{% endblock %}

hpt/core/templates/change_password_results.html
{% extends "base.html" %}

{% block content %}

{% if results %}
    <pre>
    {{ results }}
    </pre>
{% else %}
    <p>Nothing matched your search criteria.</p>
{% endif %}
{% endblock %}

hpt/core/templates/show_clock_form.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <!--
        <fieldset class="grp-module wide">
            <div class="grp-row grp-cells-1 username ">
                <div class="l-2c-fluid l-d-4">
                    <div class="c-1">
                        <label class="required" for="id_devices">Devices</label>
                    </div>
                    <div class="c-2">
                        <textarea id="id_devices" maxlength="30" name="devices" type="text" />
                            <p class="grp-help">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</p></div></div></div><div class="grp-row grp-cells-1 password1 "><div class="l-2c-fluid l-d-4"><div class="c-1"><label class="required" for="id_password1">Password</label></div><div class="c-2"><input id="id_password1" name="password1" type="password" /></div></div></div><div class="grp-row grp-cells-1 password2 "><div class="l-2c-fluid l-d-4"><div class="c-1"><label class="required" for="id_password2">Password confirmation</label></div><div class="c-2"><input id="id_password2" name="password2" type="password" /><p class="grp-help">Enter the same password as above, for verification.</p></div></div></div></fieldset>
        -->
        <!--
        <table>
            {{ form.as_table }}
        </table>
        -->
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" value="Change Password!">
    </form>
{% endblock %}